<?php

namespace br\com\InstaCambio\Stub\Goutte;

class StubFilePaths
{
    public $filePaths = [
        'http://www.example.com/' => 'foreign-currency/example.html',
        'http://www.primecash.com.br/produtos.html?shop_cat=2' => 'foreign-currency/prime-cash.html',
        'http://www.fastmoneytour.com.br/cotacao-de-moeda-fast-money-tour.php' => 'foreign-currency/fast-money.html',
        'http://www.ecofortecambioeturismo.com.br/' => 'foreign-currency/ecoforte.html',
        'http://www.amazoniacambio.com.br/site_2013/' => 'foreign-currency/amazonia.html',
        'http://www.3av.com.br/index.php/produtos-de-cambio/moedas-em-destaque' => 'foreign-currency/threeav.html',
        'http://www.cambiocorretora.com.br/' => 'foreign-currency/dibran.html',
        'http://www.torrecambio.com.br/MoedaEspecie.aspx' => 'foreign-currency/torre.html',
        'http://startcambio.com.br/comprar-moedas.html?limit=36' => 'foreign-currency/start-trips.html',
        'http://www.sagiturturismo.com.br/' => 'foreign-currency/sagitur.html',
        'http://www.cambiorapido.com/tabelinha_wl.asp?filial=144%20CALLCENTER' => 'foreign-currency/ourominas.html',
        'http://agkcorretora.com.br/pagina/cotacoes-e-simulador' => 'foreign-currency/agk.html',
        'http://bestmoney.tur.br/' => 'foreign-currency/best-money.html',
        'https://www.spmundi.com.br/moedas-em-especie' => 'foreign-currency/sp-mundi.html',
        'http://arrmcambio.com.br/?page_id=326' => 'foreign-currency/arrm.html',
        'http://thalercambio.com.br/cotacao.php' => 'foreign-currency/thaler.html',
        'http://foxcambio.com.br/' => 'foreign-currency/fox-cambio.html',
        'https://www.gradualinvestimentos.com.br/Investimentos/Cambio.aspx' => 'foreign-currency/gradual.html',
        'http://greencambio.com.br/' => 'foreign-currency/green.html',
        'https://lojavirtual.maximacambio.com.br/lojamaxima/carga.aspx' => 'foreign-currency/maxima.html',
        'https://www.picchionicambiovirtual.com.br/' => 'foreign-currency/picchioni.html',
        'http://www.goldenmoney.com.br/' => 'foreign-currency/golden-money.html',
        'https://www.xchange.com.br/produtosInternos_moedas.html' => 'foreign-currency/europa.html',
        'https://www.xchange.com.br/produtosInternos_vtm.html' => 'currency-card/europa.html',
        'http://gracoexchange.com.br/Vitrine.aspx' => 'foreign-currency/graco.html',
        'http://www.conexioncambio.com.br/' => 'foreign-currency/conexion.html',
        'https://cambiostore.com/aid=2?shop_cat=1' => 'foreign-currency/cambio-store.html',
        'http://www.ecofortecambioeturismo.com.br/produtos/visa-travel-money' => 'currency-card/ecoforte.html',
        'http://www.primecash.com.br/produtos.html?shop_cat=1' => 'currency-card/prime-cash.html',
        'http://www.casaalianca.com.br/novosite/' => 'foreign-currency/casa-alianca.html',
        'http://www.premiumviagens.com.br/cotacao.asp' => 'foreign-currency/premium-viagens.html',
        'http://tempolivretur.com.br/' => 'foreign-currency/tempo-livre.html',
        'http://local.casaalianca.com.br/teosys/cotacao_tabela_site.asp' => 'foreign-currency/amitur.html',
        'http://www.onebarra.com.br/cambio.php' => 'foreign-currency/one-barra.html',
        'http://www.dantur.com.br/novo/cambio/' => 'foreign-currency/dantur.html',
        'http://www.4cantoscambio.com.br/PapelMoeda.aspx' => 'foreign-currency/quatro-cantos.html',
        'http://ipanemaexchange.com.br/loja/pt/13-moedas' => 'foreign-currency/ipanema-exchange.html',
        'http://www.ultramarviagens.com.br/cambio' => 'foreign-currency/ultramar.html',
        'http://www.lebonvoyage.com.br/agencias/' => 'foreign-currency/le-bon-voyage.html',
        'http://www.pmturismo.com.br/site_novo/moedas.php' => 'foreign-currency/pm-turismo.html',
        'http://api.agencianavegantes.com.br/tabela.php' => 'foreign-currency/navegantes.html',
        'http://www.expresschange.tur.br/' => 'foreign-currency/express-change.html',
        'http://lygtur.com.br/mag_lygtur/' => 'currency-card/lygtur.html',
        'https://evtm.com.br/Vitrine.aspx?Moeda=Papel' => 'foreign-currency/dg.html',
        'http://www.torrecambio.com.br/CartaoVisa.aspx' => 'currency-card/torre.html',
        'https://www.spmundi.com.br/travel-card' => 'currency-card/sp-mundi.html',
        'https://cambiostore.com/aid=2?shop_cat=2' => 'currency-card/cambio-store.html',
        'http://mondialmoney.com.br/produtos.html?shop_cat=2' => 'foreign-currency/mondial-money.html',
        'http://mondialmoney.com.br/produtos.html?shop_cat=1' => 'currency-card/mondial-money.html',
        'http://www.guitta.com.br/turismo.php' => 'foreign-currency/guitta.html',
        'http://cambioevistos.com.br/cotacoes-diarias/' => 'foreign-currency/ds.html',
        'http://www.sita.com.br/site/#' => 'foreign-currency/sita.html',
        'https://evtm.com.br/Vitrine.aspx?Moeda=Visa' => 'currency-card/dg.html',
        'https://www.beecambio.com.br/cotacao-turismo/preco' => 'foreign-currency/bee-cambio.html',
        'http://cambiocuritiba.com/' => 'foreign-currency/cambio-curitiba.html',
        'http://www.sidney.com.br/cambio/cambio.aspx' => 'foreign-currency/sidney.html',
        'http://www.ebadival.com.br/cambio' => 'foreign-currency/ebadival.html',
        'https://www.avsturismo.com.br/?view=cambio' => 'foreign-currency/avs.html',
        'http://www.dourada.com.br/?/cotacao/' => 'foreign-currency/dourada.html',
        'http://ofranco.com.br/' => 'foreign-currency/oliveira-franco.html',
        'http://www.forturcambio.com.br/' => 'foreign-currency/fortur.html',
        'http://www.sadoc.com.br/index.php?pag=pacote10' => 'foreign-currency/sadoc.html',
        'http://www.faircambiofortaleza.com.br/' => 'foreign-currency/fair-cambio.html',
        'http://www.tourstar.tur.br/' => 'foreign-currency/tour-star.html',
        'http://www.afetur.com.br/default.asp' => 'foreign-currency/afetur.html',
        'http://www.toppingtur.com.br/' => 'foreign-currency/toppingtur.html',
        'http://eurocambio.tur.br/' => 'foreign-currency/euro-cambio.html',
        'http://www.cearatravel.com.br/site/' => 'foreign-currency/ceara-travel.html',
        'http://www.luzaturismo.com.br/' => 'foreign-currency/luza.html',
        'https://sistema.cambionet.com/lojavirtual/Carga.aspx' => 'foreign-currency/cambio-net.html',
        'http://faircambiopoa.com.br/cotacoes/' => 'foreign-currency/fair-cambio-poa.html',
        'http://www.ctrcambio.com.br/novo/?page_id=10' => 'foreign-currency/ctr.html',
        'http://cambioideal.com.br/cotacoes/' => 'foreign-currency/ideal.html',
        'http://montevideucambio.com.br/cotacao.php' => 'foreign-currency/montevideu.html',
        'http://www.exim.com.br' => 'foreign-currency/exim.html',
        'http://www.shoppingtourbahia.com.br/' => 'foreign-currency/shopping-tour.html',
        'http://www.caroldtvm.com.br/' => 'foreign-currency/carol.html',
        'http://www.lojamultimoney.com.br/MoedasEspecie.aspx' => 'foreign-currency/multi-money.html',
        'http://www.lojamultimoney.com.br/CartaoViagem.aspx' => 'currency-card/multi-money.html',
        'http://alphacambio.com/' => 'foreign-currency/alpha-cambio.html',
        'http://www.turvicam.com.br/index.php' => 'foreign-currency/turvicam.html',
        'http://www.monopoliocambio.com.br/' => 'foreign-currency/monopolio.html',
        'http://www.dinastur.com.br/' => 'foreign-currency/dinastur.html',
        'http://www.lhx.com.br/#!casa-de-cambio/cms9' => 'foreign-currency/lhx.html',
        'http://www.foxcambio.com.br/2013/tabelinha.asp?externo=sim&filialtaxa=campogrande%20i' => 'foreign-currency/voe-viagens.html',
        'http://www.pontalturismo.com.br/' => 'foreign-currency/pontal-turismo.html',
        'https://docs.google.com/spreadsheets/d/1A6cThSvMoLK8DDY1a3fvFuE1MgO-B38bwzVmtxOKRAg/pubhtml/sheet?headers=false&gid=0' => 'foreign-currency/ivoramtur.html',
        'http://acorianacorretora.com.br/home' => 'foreign-currency/acoriana.html',
        'http://www.alohacambio.com.br/pg/26504/inicial/' => 'foreign-currency/aloha-cambio.html',
        'http://www.foxcambio.com.br/2013/tabelinha.asp?FilialTaxa=VILA%20VELHA&externo=sim' => 'foreign-currency/turismo-dez.html',
        'https://www.lastro.com.br/produtos' => 'currency-card/lastro.html',
        'http://www.gmtcambio.com.br/' => 'foreign-currency/gmt.html',
        'http://www.cagifinabc.com.br/?page_id=1369' => 'foreign-currency/cagifin-abc.html',
        'http://numatur.com.br/ncc-cambio/' => 'foreign-currency/numatur.html',
        'http://www.lojamultimoney.com.br/?interpolo' => 'foreign-currency/interpolo.html',
        'http://sidney.com.br/cambio/cambio.aspx?c=2' => 'foreign-currency/sidney-londrina.html',
    ];

}